"""Generate docs/traceability.md by scanning the codebase for requirement IDs.

Hand-maintained coverage matrices drift: a rule gets renamed, a test gets
deleted, and the table still claims green. This derives the matrix from what is
actually in the tree, and exits non-zero when a buildable requirement has no
test — so an untested requirement fails a build rather than surviving to
submission.

Convention: a requirement ID appears in the docstring or a comment of the code
that implements it, and in the name or docstring of the test that covers it.
`VAL-04` and `val_04` are treated as the same identifier, so
`test_val_04_warning_body_not_bold` counts.

    python scripts/gen_traceability.py [--check]
"""

import argparse
import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).parent.parent
DOCS = ROOT / "docs"
ID_RE = re.compile(r"\b([A-Z]{3})-(\d{2})\b")


def variants(req_id: str) -> tuple[str, str]:
    """`VAL-04` also appears as `val_04` inside test function names."""
    return req_id, req_id.lower().replace("-", "_")


def expand_ranges(text: str) -> str:
    """Rewrite `VAL-01..09` as the individual IDs so range notation counts."""
    def grow(match: re.Match) -> str:
        prefix, lo, hi = match.group(1), int(match.group(2)), int(match.group(3))
        return " ".join(f"{prefix}-{n:02d}" for n in range(lo, hi + 1))

    return re.sub(r"\b([A-Z]{3})-(\d{2})\.\.(\d{2})\b", grow, text)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="Fail if any buildable requirement lacks a test; write nothing")
    args = parser.parse_args()

    requirements = (DOCS / "requirements.md").read_text(encoding="utf-8")
    rows = re.findall(r"^\| ([A-Z]{3}-\d{2}) \| (.+?) \|", requirements, re.M)
    ids = [rid for rid, _ in rows]
    buildable = [rid for rid in ids if not rid.startswith("OOS")]

    src_files = sorted(ROOT.glob("app/**/*.py"))
    test_files = sorted(ROOT.glob("tests/**/*.py"))
    all_web = sorted(ROOT.glob("web/src/**/*.js*"))
    web_tests = [p for p in all_web if ".test." in p.name]
    web_files = [p for p in all_web if ".test." not in p.name]
    script_files = sorted(ROOT.glob("scripts/*.py"))

    def scan_expanded(paths: list[Path]) -> dict[str, set[str]]:
        found: dict[str, set[str]] = defaultdict(set)
        for path in paths:
            text = expand_ranges(path.read_text(encoding="utf-8"))
            for req_id in ids:
                hyphen, underscore = variants(req_id)
                if hyphen in text or underscore in text:
                    found[req_id].add(path.relative_to(ROOT).as_posix())
        return found

    impl = scan_expanded(src_files + web_files)
    tests = scan_expanded(test_files + web_tests)
    scripts = scan_expanded(script_files)

    verified = {rid for rid in buildable if tests.get(rid) or scripts.get(rid)}
    untested = [
        rid for rid in buildable
        if rid not in verified and not rid.startswith(("DEL", "OPS-03", "OPS-06"))
    ]

    if args.check:
        if untested:
            print("requirements with no covering test:")
            for rid in untested:
                print(f"  {rid}")
            return 1
        print(f"all {len(buildable)} buildable requirements have a covering test or a documented exemption")
        return 0

    lines = [
        "# Traceability matrix",
        "",
        "Generated by `scripts/gen_traceability.py`. Do not edit by hand.",
        "",
        "A requirement ID appears in the docstring or comments of the code implementing it,",
        "and in the name or docstring of the test covering it, so this table is derived from",
        "the tree rather than maintained alongside it. `scripts/gen_traceability.py --check`",
        "fails when a buildable requirement has no test.",
        "",
        "Status is `test` where a unit or API test names the requirement, `measured` where it is",
        "verified by a script whose output is recorded (latency and real-image extraction cannot",
        "be asserted without an API call), and `deliverable` for the README, the deployed URL",
        "and the submission itself.",
        "",
        "| ID | Requirement | Implementation | Test | Status |",
        "|---|---|---|---|---|",
    ]

    for rid, desc in rows:
        desc = re.sub(r"\*\*(.+?)\*\*", r"\1", desc).strip()
        if len(desc) > 66:
            desc = desc[:63].rstrip() + "…"

        if rid.startswith("OOS"):
            lines.append(f"| {rid} | {desc} | — | — | out of scope |")
            continue

        impl_files = sorted(impl.get(rid, ()))
        test_files_for_id = sorted(tests.get(rid, ()))
        impl_text = "<br>".join(f"`{p}`" for p in impl_files) or "—"
        test_text = "<br>".join(f"`{p.split('/')[-1]}`" for p in test_files_for_id) or "—"

        script_files_for_id = sorted(scripts.get(rid, ()))
        if test_files_for_id:
            status = "test"
        elif script_files_for_id:
            # Latency and real-image extraction cannot be asserted in a unit test
            # without an API call; they are measured, and the measurement is recorded.
            status = "measured"
            test_text = "<br>".join(f"`{p.split('/')[-1]}`" for p in script_files_for_id)
        elif rid.startswith(("DEL", "OPS-03", "OPS-06")):
            status = "deliverable"
        else:
            status = "**none**"

        lines.append(f"| {rid} | {desc} | {impl_text} | {test_text} | {status} |")

    by_test = sum(1 for rid in buildable if tests.get(rid))
    by_script = sum(1 for rid in buildable if not tests.get(rid) and scripts.get(rid))
    remainder = len(buildable) - by_test - by_script
    lines += [
        "",
        f"**{by_test}** verified by automated test · **{by_script}** by recorded measurement "
        f"(`docs/perf.md`, `docs/verification.md`) · **{remainder}** satisfied by the "
        f"deliverable itself, of {len(buildable)} buildable requirements.",
    ]

    (DOCS / "traceability.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote docs/traceability.md — {by_test} tested, {by_script} measured, of {len(buildable)}")
    if untested:
        print("unverified:", ", ".join(untested))
    return 0


if __name__ == "__main__":
    sys.exit(main())
